"""empty message

Revision ID: 564826a79a66
Revises: c2977653b3df
Create Date: 2018-07-17 18:21:03.400433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564826a79a66'
down_revision = 'c2977653b3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('lembaga_name', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'lembaga_name')
    # ### end Alembic commands ###
