"""empty message

Revision ID: 77bee8515c8e
Revises: 
Create Date: 2018-08-09 23:20:48.662253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bee8515c8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lembagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=False),
    sa.Column('penanggung_jawab', sa.String(length=100), nullable=True),
    sa.Column('nomor_hp', sa.String(length=25), nullable=True),
    sa.Column('id_line', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('instagram', sa.String(length=250), nullable=True),
    sa.Column('web', sa.String(length=250), nullable=True),
    sa.Column('youtube', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('lembaga_id', sa.Integer(), nullable=False),
    sa.Column('lembaga_name', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['lembaga_id'], ['lembagas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('lembagas')
    op.drop_table('categories')
    # ### end Alembic commands ###
