"""empty message

Revision ID: c2977653b3df
Revises: 25be96c5086e
Create Date: 2018-07-09 23:43:02.924672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2977653b3df'
down_revision = '25be96c5086e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lembagas', sa.Column('email', sa.String(length=250), nullable=True))
    op.add_column('lembagas', sa.Column('id_line', sa.String(length=250), nullable=True))
    op.add_column('lembagas', sa.Column('instagram', sa.String(length=250), nullable=True))
    op.add_column('lembagas', sa.Column('nomor_hp', sa.String(length=25), nullable=True))
    op.add_column('lembagas', sa.Column('penanggung_jawab', sa.String(length=100), nullable=True))
    op.add_column('lembagas', sa.Column('web', sa.String(length=250), nullable=True))
    op.add_column('lembagas', sa.Column('youtube', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lembagas', 'youtube')
    op.drop_column('lembagas', 'web')
    op.drop_column('lembagas', 'penanggung_jawab')
    op.drop_column('lembagas', 'nomor_hp')
    op.drop_column('lembagas', 'instagram')
    op.drop_column('lembagas', 'id_line')
    op.drop_column('lembagas', 'email')
    # ### end Alembic commands ###
