"""empty message

Revision ID: c977553679e2
Revises: 77bee8515c8e
Create Date: 2018-08-12 14:23:58.505793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c977553679e2'
down_revision = '77bee8515c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('description', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('goal', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('target', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'time')
    op.drop_column('activities', 'target')
    op.drop_column('activities', 'goal')
    op.drop_column('activities', 'description')
    op.drop_column('activities', 'category_id')
    # ### end Alembic commands ###
